/** Sample rows for USELY_OPS_MOCK — never touches Supabase. */
export const OPS_MOCK_ORGS = [
  {
    id: "ops-mock-1",
    name: "Astral Rust",
    slug: "astral",
    plan: "pro",
    plan_status: "active",
    created_at: "2026-06-12T14:22:00.000Z",
    owner_email: "owner@astral.example",
    server_count: 3,
  },
  {
    id: "ops-mock-2",
    name: "Nightfall Network",
    slug: "nightfall",
    plan: "network",
    plan_status: "trialing",
    created_at: "2026-07-01T09:10:00.000Z",
    owner_email: "admin@nightfall.example",
    server_count: 8,
  },
  {
    id: "ops-mock-3",
    name: "Copper Basin",
    slug: "copper",
    plan: "basic",
    plan_status: "active",
    created_at: "2026-07-18T18:40:00.000Z",
    owner_email: "hello@copper.example",
    server_count: 1,
  },
  {
    id: "ops-mock-4",
    name: "Dustbowl Duo",
    slug: "dustbowl",
    plan: "basic",
    plan_status: "past_due",
    created_at: "2026-07-22T11:05:00.000Z",
    owner_email: "bills@dustbowl.example",
    server_count: 2,
  },
  {
    id: "ops-mock-5",
    name: "Ghost Town",
    slug: "ghosttown",
    plan: "pro",
    plan_status: "canceled",
    created_at: "2026-05-03T20:00:00.000Z",
    owner_email: "old@ghost.example",
    server_count: 0,
  },
];
